### PR TITLE
Add ability to randomize questions

### PR DESCRIPTION
**Pull request by SergeyYukhnevich**
This changes will work only with this [library](https://github.com/SergeyYukhnevich/h5p-randomize).

### CODE REVIEW

**Comment by timothyylim** [comment]
Thanks, this is a wonderfully clean solution.

You may have missed the fact that H5P core has a shuffle function:

https://github.com/h5p/h5p-php-library/blob/5b8836b5bef1a2e1187c6d1c707d629f1c3a5bec/js/h5p.js#L1606

Therefore, it may not be advisable for us to duplicate functionality by integrating H5P.Randomize.

We are currently working on something similar but with a few additional requirements:

https://h5ptechnology.atlassian.net/browse/HFP-56

and the work so far can be found on the following branch:

https://github.com/h5p/h5p-question-set/commits/randomize-questions

If you have the time, we are open to any comments and suggestions for improvements.

**Comment by SergeyYukhnevich** [comment]
@timothyylim Thank you! The idea was a bit different from just sort the questions in different order. It was to add ability to the user to create as much questions as they want and show only specific amount of created question in random order.

But anyway if you need any code from my solution feel free to use it.

**Comment by timothyylim** [comment]
Thanks, we'll think about what we can learn from this in the next release.

**Comment by timothyylim** [comment]
Closing this pull request as randomization has been added: https://github.com/h5p/h5p-question-set/commit/6d4a915de19a7ebf8dfbe9ac071f92634f2f8516

**Pull request closed without merging**
